"use strict";(self.webpackChunkbsign_ui=self.webpackChunkbsign_ui||[]).push([[892],{33001:function(c,s,e){e.r(s),e.d(s,{demos:function(){return h}});var i=e(17061),d=e.n(i),v=e(17156),p=e.n(v),t=e(67294),E=e(50940),g=e(82883),h={"emptyui-demo-0":{component:t.memo(t.lazy(p()(d()().mark(function m(){var l,o,r,u,I;return d()().wrap(function(n){for(;;)switch(n.prev=n.next){case 0:return n.next=2,Promise.resolve().then(e.bind(e,50940));case 2:return l=n.sent,o=l.Space,n.next=6,Promise.resolve().then(e.bind(e,82883));case 6:return r=n.sent,u=r.EmptyUI,I=r.ImageUI,n.abrupt("return",{default:function(){return t.createElement(o,null,t.createElement(u,null),t.createElement(u,{image:t.createElement(I,{src:"https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",width:177,height:144})}),t.createElement(u,{text:"\u6682\u65E0\u6570\u636E"}))}});case 10:case"end":return n.stop()}},m)})))),asset:{type:"BLOCK",id:"emptyui-demo-0",refAtomIds:["EmptyUI"],dependencies:{"index.tsx":{type:"FILE",value:`import { Space } from 'antd';
import { EmptyUI, ImageUI } from 'bsign-ui';

export default () => (
  <Space>
    <EmptyUI />
    <EmptyUI
      image={<ImageUI src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png" width={177} height={144} />}
    />
    <EmptyUI text="\u6682\u65E0\u6570\u636E" />
  </Space>
);`},antd:{type:"NPM",value:"6.0.0"},"bsign-ui":{type:"NPM",value:"0.0.1"}},entry:"index.tsx"},context:{antd:E,"bsign-ui":g},renderOpts:{compile:function(){var m=p()(d()().mark(function o(){var r,u=arguments;return d()().wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,e.e(250).then(e.bind(e,90250));case 2:return a.abrupt("return",(r=a.sent).default.apply(r,u));case 3:case"end":return a.stop()}},o)}));function l(){return m.apply(this,arguments)}return l}()}}}},85005:function(c,s,e){e.r(s),e.d(s,{texts:function(){return i}});const i=[{value:"\u{1F48E} \u57FA\u7840\u4F7F\u7528",paraId:0,tocIndex:0},{value:"EmptyUI",paraId:1,tocIndex:1},{value:"\u5C5E\u6027",paraId:2,tocIndex:1},{value:"\u8BF4\u660E",paraId:2,tocIndex:1},{value:"\u7C7B\u578B",paraId:2,tocIndex:1},{value:"\u9ED8\u8BA4\u503C",paraId:2,tocIndex:1},{value:"\u662F\u5426\u5FC5\u4F20",paraId:2,tocIndex:1},{value:"className",paraId:2,tocIndex:1},{value:"\u7C7B\u540D",paraId:2,tocIndex:1},{value:"String",paraId:2,tocIndex:1},{value:"-",paraId:2,tocIndex:1},{value:"\u5426",paraId:2,tocIndex:1},{value:"text",paraId:2,tocIndex:1},{value:"\u6587\u6848",paraId:2,tocIndex:1},{value:"String",paraId:2,tocIndex:1},{value:"-",paraId:2,tocIndex:1},{value:"\u5426",paraId:2,tocIndex:1}]}}]);
