"use strict";(self.webpackChunkbsign_ui=self.webpackChunkbsign_ui||[]).push([[3996],{46720:function(c,t,e){var u;e.r(t),e.d(t,{demos:function(){return O}});var v=e(17061),o=e.n(v),g=e(27424),f=e.n(g),E=e(17156),m=e.n(E),l=e(67294),h=e(82883),O={"loadingui-demo-0":{component:l.memo(l.lazy(m()(o()().mark(function _(){var r,d,s,i,I,n;return o()().wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,Promise.resolve().then(e.t.bind(e,67294,19));case 2:return r=a.sent,d=r.default,s=r.useState,a.next=7,Promise.resolve().then(e.bind(e,82883));case 7:return i=a.sent,I=i.LoadingUI,n=function(){var P=s(!1),p=f()(P,2),L=p[0],b=p[1],y=function(){return b(!1)};return d.createElement(I,{isShowLoading:!0})},a.abrupt("return",{default:n});case 11:case"end":return a.stop()}},_)})))),asset:{type:"BLOCK",id:"loadingui-demo-0",refAtomIds:["LoadingUI"],dependencies:{"index.tsx":{type:"FILE",value:`import React, { useState } from 'react';
import { Space } from 'antd';
import { LoadingUI } from 'bsign-ui';

const App: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const confirm = () => setIsOpen(false);
  return <LoadingUI isShowLoading={true} />;
};
export default App;`},react:{type:"NPM",value:"18.3.1"},"bsign-ui":{type:"NPM",value:"0.0.3"}},entry:"index.tsx"},context:{react:u||(u=e.t(l,2)),"bsign-ui":h},renderOpts:{compile:function(){var _=m()(o()().mark(function d(){var s,i=arguments;return o()().wrap(function(n){for(;;)switch(n.prev=n.next){case 0:return n.next=2,e.e(250).then(e.bind(e,90250));case 2:return n.abrupt("return",(s=n.sent).default.apply(s,i));case 3:case"end":return n.stop()}},d)}));function r(){return _.apply(this,arguments)}return r}()}}}},67933:function(c,t,e){e.r(t),e.d(t,{texts:function(){return u}});const u=[{value:"\u52A0\u8F7D\u4E2D\u7EC4\u4EF6",paraId:0},{value:"\u{1F48E} \u57FA\u7840\u4F7F\u7528",paraId:1,tocIndex:1},{value:"\u5C5E\u6027",paraId:2,tocIndex:2},{value:"\u8BF4\u660E",paraId:2,tocIndex:2},{value:"\u7C7B\u578B",paraId:2,tocIndex:2},{value:"\u9ED8\u8BA4\u503C",paraId:2,tocIndex:2},{value:"\u662F\u5426\u5FC5\u4F20",paraId:2,tocIndex:2},{value:"type",paraId:2,tocIndex:2},{value:"\u5F53\u524D TagUI \u6240\u5C5E\u7C7B\u578B",paraId:2,tocIndex:2},{value:"Number",paraId:2,tocIndex:2},{value:"-",paraId:2,tocIndex:2},{value:"\u5426",paraId:2,tocIndex:2},{value:"icon",paraId:2,tocIndex:2},{value:"\u5F53\u524D TagUI \u6240 \u643A\u5E26\u7684 Icon",paraId:2,tocIndex:2},{value:"ReactNode",paraId:2,tocIndex:2},{value:"-",paraId:2,tocIndex:2},{value:"\u5426",paraId:2,tocIndex:2}]}}]);
